@server = http://localhost:4004
@auth = Authorization: Basic alice:


### MDM.LinesOfBusiness
GET {{server}}/odata/v4/mdm/LinesOfBusiness
Content-Type: application/json
{{auth}}


### MDM.LinesOfBusiness
POST {{server}}/odata/v4/mdm/LinesOfBusiness
Content-Type: application/json
{{auth}}

{
  "ID": 16899971,
  "createdAt": "2008-12-04T20:00:00.000Z",
  "createdBy": "createdBy-16899971",
  "modifiedAt": "2023-04-26T20:00:00.000Z",
  "modifiedBy": "modifiedBy-16899971",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_NAME": "LOB_NAME-16899971",
  "LOB_DESCRIPTION": "LOB_DESCRIPTION-16899971",
  "BILLING_POLICY_TYPE": "71"
}


### MDM.LinesOfBusiness
PATCH {{server}}/odata/v4/mdm/LinesOfBusiness/16899971
Content-Type: application/json
{{auth}}

{
  "ID": 16899971,
  "createdAt": "2008-12-04T20:00:00.000Z",
  "createdBy": "createdBy-16899971",
  "modifiedAt": "2023-04-26T20:00:00.000Z",
  "modifiedBy": "modifiedBy-16899971",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_NAME": "LOB_NAME-16899971",
  "LOB_DESCRIPTION": "LOB_DESCRIPTION-16899971",
  "BILLING_POLICY_TYPE": "71"
}


### MDM.LinesOfBusiness
DELETE {{server}}/odata/v4/mdm/LinesOfBusiness/16899971
Content-Type: application/json
{{auth}}


### MDM.AgreementStatuses
GET {{server}}/odata/v4/mdm/AgreementStatuses
Content-Type: application/json
{{auth}}


### MDM.AgreementStatuses
POST {{server}}/odata/v4/mdm/AgreementStatuses
Content-Type: application/json
{{auth}}

{
  "ID": 3582484,
  "createdAt": "2001-04-09T20:00:00.000Z",
  "createdBy": "createdBy-3582484",
  "modifiedAt": "2014-12-06T20:00:00.000Z",
  "modifiedBy": "modifiedBy-3582484",
  "ACTIVE": true,
  "DELETED": true,
  "STATUS_KEY": "STATUS_KEY-3582484",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-3582484"
}


### MDM.AgreementStatuses
PATCH {{server}}/odata/v4/mdm/AgreementStatuses/3582484
Content-Type: application/json
{{auth}}

{
  "ID": 3582484,
  "createdAt": "2001-04-09T20:00:00.000Z",
  "createdBy": "createdBy-3582484",
  "modifiedAt": "2014-12-06T20:00:00.000Z",
  "modifiedBy": "modifiedBy-3582484",
  "ACTIVE": true,
  "DELETED": true,
  "STATUS_KEY": "STATUS_KEY-3582484",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-3582484"
}


### MDM.AgreementStatuses
DELETE {{server}}/odata/v4/mdm/AgreementStatuses/3582484
Content-Type: application/json
{{auth}}


### MDM.AgreementTypes
GET {{server}}/odata/v4/mdm/AgreementTypes
Content-Type: application/json
{{auth}}


### MDM.AgreementTypes
POST {{server}}/odata/v4/mdm/AgreementTypes
Content-Type: application/json
{{auth}}

{
  "ID": 28659033,
  "createdAt": "2004-04-05T20:00:00.000Z",
  "createdBy": "createdBy-28659033",
  "modifiedAt": "2004-02-29T20:00:00.000Z",
  "modifiedBy": "modifiedBy-28659033",
  "ACTIVE": false,
  "DELETED": false,
  "AGREEMENTTYPE_KEY": "ENTTYPE_KEY-28659033",
  "AGREEMENTTYPE_DESCRIPTION": "AGREEMENTTYPE_DESCRIPTION-28659033"
}


### MDM.AgreementTypes
PATCH {{server}}/odata/v4/mdm/AgreementTypes/28659033
Content-Type: application/json
{{auth}}

{
  "ID": 28659033,
  "createdAt": "2004-04-05T20:00:00.000Z",
  "createdBy": "createdBy-28659033",
  "modifiedAt": "2004-02-29T20:00:00.000Z",
  "modifiedBy": "modifiedBy-28659033",
  "ACTIVE": false,
  "DELETED": false,
  "AGREEMENTTYPE_KEY": "ENTTYPE_KEY-28659033",
  "AGREEMENTTYPE_DESCRIPTION": "AGREEMENTTYPE_DESCRIPTION-28659033"
}


### MDM.AgreementTypes
DELETE {{server}}/odata/v4/mdm/AgreementTypes/28659033
Content-Type: application/json
{{auth}}


### MDM.Coverholders
GET {{server}}/odata/v4/mdm/Coverholders
Content-Type: application/json
{{auth}}


### MDM.Coverholders
POST {{server}}/odata/v4/mdm/Coverholders
Content-Type: application/json
{{auth}}

{
  "ID": 18634168,
  "createdAt": "2011-01-08T20:00:00.000Z",
  "createdBy": "createdBy-18634168",
  "modifiedAt": "2013-10-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-18634168",
  "ACTIVE": true,
  "DELETED": true,
  "COVERHOLDER_CODE": "HOLDER_CODE-18634168",
  "COVERHOLDER_NAME": "COVERHOLDER_NAME-18634168",
  "COVERHOLDER_PIN": "COVERHOLDER_PIN-18634168"
}


### MDM.Coverholders
PATCH {{server}}/odata/v4/mdm/Coverholders/18634168
Content-Type: application/json
{{auth}}

{
  "ID": 18634168,
  "createdAt": "2011-01-08T20:00:00.000Z",
  "createdBy": "createdBy-18634168",
  "modifiedAt": "2013-10-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-18634168",
  "ACTIVE": true,
  "DELETED": true,
  "COVERHOLDER_CODE": "HOLDER_CODE-18634168",
  "COVERHOLDER_NAME": "COVERHOLDER_NAME-18634168",
  "COVERHOLDER_PIN": "COVERHOLDER_PIN-18634168"
}


### MDM.Coverholders
DELETE {{server}}/odata/v4/mdm/Coverholders/18634168
Content-Type: application/json
{{auth}}


### MDM.Countries
GET {{server}}/odata/v4/mdm/Countries
Content-Type: application/json
{{auth}}


### MDM.Countries
POST {{server}}/odata/v4/mdm/Countries
Content-Type: application/json
{{auth}}

{
  "ID": 575840,
  "createdAt": "2014-06-14T20:00:00.000Z",
  "createdBy": "createdBy-575840",
  "modifiedAt": "2008-04-18T20:00:00.000Z",
  "modifiedBy": "modifiedBy-575840",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "840",
  "COUNTRY_NAME": "COUNTRY_NAME-575840",
  "FLAG_URL": "FLAG_URL-575840"
}


### MDM.Countries
PATCH {{server}}/odata/v4/mdm/Countries/575840
Content-Type: application/json
{{auth}}

{
  "ID": 575840,
  "createdAt": "2014-06-14T20:00:00.000Z",
  "createdBy": "createdBy-575840",
  "modifiedAt": "2008-04-18T20:00:00.000Z",
  "modifiedBy": "modifiedBy-575840",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "840",
  "COUNTRY_NAME": "COUNTRY_NAME-575840",
  "FLAG_URL": "FLAG_URL-575840"
}


### MDM.Countries
DELETE {{server}}/odata/v4/mdm/Countries/575840
Content-Type: application/json
{{auth}}


### MDM.Segments
GET {{server}}/odata/v4/mdm/Segments
Content-Type: application/json
{{auth}}


### MDM.Segments
POST {{server}}/odata/v4/mdm/Segments
Content-Type: application/json
{{auth}}

{
  "ID": 12825763,
  "createdAt": "2008-10-15T20:00:00.000Z",
  "createdBy": "createdBy-12825763",
  "modifiedAt": "2012-08-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12825763",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 1,
  "SEGMENT_NAME": "SEGMENT_NAME-12825763",
  "SEGMENT_DESCRIPTION": "SEGMENT_DESCRIPTION-12825763"
}


### MDM.Segments
PATCH {{server}}/odata/v4/mdm/Segments/12825763
Content-Type: application/json
{{auth}}

{
  "ID": 12825763,
  "createdAt": "2008-10-15T20:00:00.000Z",
  "createdBy": "createdBy-12825763",
  "modifiedAt": "2012-08-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12825763",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 1,
  "SEGMENT_NAME": "SEGMENT_NAME-12825763",
  "SEGMENT_DESCRIPTION": "SEGMENT_DESCRIPTION-12825763"
}


### MDM.Segments
DELETE {{server}}/odata/v4/mdm/Segments/12825763
Content-Type: application/json
{{auth}}


### MDM.Pools
GET {{server}}/odata/v4/mdm/Pools
Content-Type: application/json
{{auth}}


### MDM.Pools
POST {{server}}/odata/v4/mdm/Pools
Content-Type: application/json
{{auth}}

{
  "ID": 8904251,
  "createdAt": "2022-04-16T20:00:00.000Z",
  "createdBy": "createdBy-8904251",
  "modifiedAt": "2005-09-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8904251",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 26,
  "POOL_NAME": "POOL_NAME-8904251",
  "POOL_DESCRIPTION": "POOL_DESCRIPTION-8904251",
  "POOL_CD": "251",
  "ItsLob": {
    "ID": 26998332
  }
}


### MDM.Pools
PATCH {{server}}/odata/v4/mdm/Pools/8904251
Content-Type: application/json
{{auth}}

{
  "ID": 8904251,
  "createdAt": "2022-04-16T20:00:00.000Z",
  "createdBy": "createdBy-8904251",
  "modifiedAt": "2005-09-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8904251",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 26,
  "POOL_NAME": "POOL_NAME-8904251",
  "POOL_DESCRIPTION": "POOL_DESCRIPTION-8904251",
  "POOL_CD": "251",
  "ItsLob": {
    "ID": 26998332
  }
}


### MDM.Pools
DELETE {{server}}/odata/v4/mdm/Pools/8904251
Content-Type: application/json
{{auth}}


### MDM.PoolUwys
GET {{server}}/odata/v4/mdm/PoolUwys
Content-Type: application/json
{{auth}}


### MDM.PoolUwys
POST {{server}}/odata/v4/mdm/PoolUwys
Content-Type: application/json
{{auth}}

{
  "ID": 5716157,
  "createdAt": "2022-02-18T20:00:00.000Z",
  "createdBy": "createdBy-5716157",
  "modifiedAt": "2023-05-10T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5716157",
  "ACTIVE": false,
  "DELETED": false,
  "POOL_ID": 29,
  "POOLUWY_NAME": "POOLUWY_NAME-5716157",
  "UWYEAR": 78,
  "INCEPTION": "2020-02-29",
  "EXPIRYDATE": "2018-11-23",
  "CURRENCY_ID": 88,
  "ItsPool": {
    "ID": 7326125
  }
}


### MDM.PoolUwys
PATCH {{server}}/odata/v4/mdm/PoolUwys/5716157
Content-Type: application/json
{{auth}}

{
  "ID": 5716157,
  "createdAt": "2022-02-18T20:00:00.000Z",
  "createdBy": "createdBy-5716157",
  "modifiedAt": "2023-05-10T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5716157",
  "ACTIVE": false,
  "DELETED": false,
  "POOL_ID": 29,
  "POOLUWY_NAME": "POOLUWY_NAME-5716157",
  "UWYEAR": 78,
  "INCEPTION": "2020-02-29",
  "EXPIRYDATE": "2018-11-23",
  "CURRENCY_ID": 88,
  "ItsPool": {
    "ID": 7326125
  }
}


### MDM.PoolUwys
DELETE {{server}}/odata/v4/mdm/PoolUwys/5716157
Content-Type: application/json
{{auth}}


### MDM.LloydsRiskCodes
GET {{server}}/odata/v4/mdm/LloydsRiskCodes
Content-Type: application/json
{{auth}}


### MDM.LloydsRiskCodes
POST {{server}}/odata/v4/mdm/LloydsRiskCodes
Content-Type: application/json
{{auth}}

{
  "ID": 20679034,
  "createdAt": "2009-01-02T20:00:00.000Z",
  "createdBy": "createdBy-20679034",
  "modifiedAt": "2010-08-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-20679034",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 20,
  "LLRISK_CODE": "LLRISK_CODE-20679034",
  "LLRISK_DESCRIPTION": "LLRISK_DESCRIPTION-20679034"
}


### MDM.LloydsRiskCodes
PATCH {{server}}/odata/v4/mdm/LloydsRiskCodes/20679034
Content-Type: application/json
{{auth}}

{
  "ID": 20679034,
  "createdAt": "2009-01-02T20:00:00.000Z",
  "createdBy": "createdBy-20679034",
  "modifiedAt": "2010-08-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-20679034",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 20,
  "LLRISK_CODE": "LLRISK_CODE-20679034",
  "LLRISK_DESCRIPTION": "LLRISK_DESCRIPTION-20679034"
}


### MDM.LloydsRiskCodes
DELETE {{server}}/odata/v4/mdm/LloydsRiskCodes/20679034
Content-Type: application/json
{{auth}}


### MDM.InternalRiskCodes
GET {{server}}/odata/v4/mdm/InternalRiskCodes
Content-Type: application/json
{{auth}}


### MDM.InternalRiskCodes
POST {{server}}/odata/v4/mdm/InternalRiskCodes
Content-Type: application/json
{{auth}}

{
  "ID": 11738170,
  "createdAt": "2014-06-05T20:00:00.000Z",
  "createdBy": "createdBy-11738170",
  "modifiedAt": "2022-11-14T20:00:00.000Z",
  "modifiedBy": "modifiedBy-11738170",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 93,
  "SEGMENT_ID": 99,
  "LLRISKCODE_ID": 48,
  "INTRISK_CODE": "INTRISK_CODE-11738170",
  "INTRISK_DESCRIPTION": "INTRISK_DESCRIPTION-11738170",
  "ItsLLoydsRiskCode": {
    "ID": 2488269
  }
}


### MDM.InternalRiskCodes
PATCH {{server}}/odata/v4/mdm/InternalRiskCodes/11738170
Content-Type: application/json
{{auth}}

{
  "ID": 11738170,
  "createdAt": "2014-06-05T20:00:00.000Z",
  "createdBy": "createdBy-11738170",
  "modifiedAt": "2022-11-14T20:00:00.000Z",
  "modifiedBy": "modifiedBy-11738170",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 93,
  "SEGMENT_ID": 99,
  "LLRISKCODE_ID": 48,
  "INTRISK_CODE": "INTRISK_CODE-11738170",
  "INTRISK_DESCRIPTION": "INTRISK_DESCRIPTION-11738170",
  "ItsLLoydsRiskCode": {
    "ID": 2488269
  }
}


### MDM.InternalRiskCodes
DELETE {{server}}/odata/v4/mdm/InternalRiskCodes/11738170
Content-Type: application/json
{{auth}}


### MDM.InternalRisksInPool
GET {{server}}/odata/v4/mdm/InternalRisksInPool
Content-Type: application/json
{{auth}}


### MDM.InternalRisksInPool
POST {{server}}/odata/v4/mdm/InternalRisksInPool
Content-Type: application/json
{{auth}}

{
  "ID": 9024702,
  "createdAt": "2009-08-22T20:00:00.000Z",
  "createdBy": "createdBy-9024702",
  "modifiedAt": "2022-09-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9024702",
  "ACTIVE": true,
  "DELETED": true,
  "POOLUWYEAR_ID": 46,
  "INTRISK_ID": 5,
  "ItsInternalRiskCode": {
    "ID": 28541830
  }
}


### MDM.InternalRisksInPool
PATCH {{server}}/odata/v4/mdm/InternalRisksInPool/9024702
Content-Type: application/json
{{auth}}

{
  "ID": 9024702,
  "createdAt": "2009-08-22T20:00:00.000Z",
  "createdBy": "createdBy-9024702",
  "modifiedAt": "2022-09-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9024702",
  "ACTIVE": true,
  "DELETED": true,
  "POOLUWYEAR_ID": 46,
  "INTRISK_ID": 5,
  "ItsInternalRiskCode": {
    "ID": 28541830
  }
}


### MDM.InternalRisksInPool
DELETE {{server}}/odata/v4/mdm/InternalRisksInPool/9024702
Content-Type: application/json
{{auth}}


### MDM.ConditionTypes
GET {{server}}/odata/v4/mdm/ConditionTypes
Content-Type: application/json
{{auth}}


### MDM.ConditionTypes
POST {{server}}/odata/v4/mdm/ConditionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 2330975,
  "createdAt": "2017-08-29T20:00:00.000Z",
  "createdBy": "createdBy-2330975",
  "modifiedAt": "2010-07-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2330975",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 72,
  "CONDITION_NAME": "CONDITION_NAME-2330975",
  "CONDITION_DESCRIPTION": "CONDITION_DESCRIPTION-2330975",
  "CONDITION_VALUE_TYPE": "CONDITION_VALUE_TYPE-2330975",
  "DEFAULT_OP_ID": 63,
  "FORMULA": "FORMULA-2330975"
}


### MDM.ConditionTypes
PATCH {{server}}/odata/v4/mdm/ConditionTypes/2330975
Content-Type: application/json
{{auth}}

{
  "ID": 2330975,
  "createdAt": "2017-08-29T20:00:00.000Z",
  "createdBy": "createdBy-2330975",
  "modifiedAt": "2010-07-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2330975",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 72,
  "CONDITION_NAME": "CONDITION_NAME-2330975",
  "CONDITION_DESCRIPTION": "CONDITION_DESCRIPTION-2330975",
  "CONDITION_VALUE_TYPE": "CONDITION_VALUE_TYPE-2330975",
  "DEFAULT_OP_ID": 63,
  "FORMULA": "FORMULA-2330975"
}


### MDM.ConditionTypes
DELETE {{server}}/odata/v4/mdm/ConditionTypes/2330975
Content-Type: application/json
{{auth}}


### MDM.EndorsementTypes
GET {{server}}/odata/v4/mdm/EndorsementTypes
Content-Type: application/json
{{auth}}


### MDM.EndorsementTypes
POST {{server}}/odata/v4/mdm/EndorsementTypes
Content-Type: application/json
{{auth}}

{
  "ID": 24671288,
  "createdAt": "2008-05-30T20:00:00.000Z",
  "createdBy": "createdBy-24671288",
  "modifiedAt": "2007-05-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24671288",
  "ACTIVE": true,
  "DELETED": true,
  "ENDORSEMENTTYPE_KEY": "ENTTYPE_KEY-24671288",
  "ENDORSEMENTTYPE_DESCRIPTION": "ENDORSEMENTTYPE_DESCRIPTION-24671288"
}


### MDM.EndorsementTypes
PATCH {{server}}/odata/v4/mdm/EndorsementTypes/24671288
Content-Type: application/json
{{auth}}

{
  "ID": 24671288,
  "createdAt": "2008-05-30T20:00:00.000Z",
  "createdBy": "createdBy-24671288",
  "modifiedAt": "2007-05-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24671288",
  "ACTIVE": true,
  "DELETED": true,
  "ENDORSEMENTTYPE_KEY": "ENTTYPE_KEY-24671288",
  "ENDORSEMENTTYPE_DESCRIPTION": "ENDORSEMENTTYPE_DESCRIPTION-24671288"
}


### MDM.EndorsementTypes
DELETE {{server}}/odata/v4/mdm/EndorsementTypes/24671288
Content-Type: application/json
{{auth}}


### MDM.Subjectivities
GET {{server}}/odata/v4/mdm/Subjectivities
Content-Type: application/json
{{auth}}


### MDM.Subjectivities
POST {{server}}/odata/v4/mdm/Subjectivities
Content-Type: application/json
{{auth}}

{
  "ID": 17185080,
  "createdAt": "2019-11-11T20:00:00.000Z",
  "createdBy": "createdBy-17185080",
  "modifiedAt": "2009-05-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-17185080",
  "ACTIVE": true,
  "DELETED": true,
  "SUBJECTIVITY_SUB_KEY": 80,
  "DESCRIPTION": "DESCRIPTION-17185080"
}


### MDM.Subjectivities
PATCH {{server}}/odata/v4/mdm/Subjectivities/17185080
Content-Type: application/json
{{auth}}

{
  "ID": 17185080,
  "createdAt": "2019-11-11T20:00:00.000Z",
  "createdBy": "createdBy-17185080",
  "modifiedAt": "2009-05-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-17185080",
  "ACTIVE": true,
  "DELETED": true,
  "SUBJECTIVITY_SUB_KEY": 80,
  "DESCRIPTION": "DESCRIPTION-17185080"
}


### MDM.Subjectivities
DELETE {{server}}/odata/v4/mdm/Subjectivities/17185080
Content-Type: application/json
{{auth}}


### MDM.Clauses
GET {{server}}/odata/v4/mdm/Clauses
Content-Type: application/json
{{auth}}


### MDM.Clauses
POST {{server}}/odata/v4/mdm/Clauses
Content-Type: application/json
{{auth}}

{
  "ID": 29197259,
  "createdAt": "2012-06-24T20:00:00.000Z",
  "createdBy": "createdBy-29197259",
  "modifiedAt": "2019-01-08T20:00:00.000Z",
  "modifiedBy": "modifiedBy-29197259",
  "ACTIVE": false,
  "DELETED": false,
  "CLAUSE_NAME": "CLAUSE_NAME-29197259",
  "CLAUSE_CODE": "CLAUSE_CODE-29197259",
  "CLAUSE_TEXT": "CLAUSE_TEXT-29197259",
  "LOB_ID": 97
}


### MDM.Clauses
PATCH {{server}}/odata/v4/mdm/Clauses/29197259
Content-Type: application/json
{{auth}}

{
  "ID": 29197259,
  "createdAt": "2012-06-24T20:00:00.000Z",
  "createdBy": "createdBy-29197259",
  "modifiedAt": "2019-01-08T20:00:00.000Z",
  "modifiedBy": "modifiedBy-29197259",
  "ACTIVE": false,
  "DELETED": false,
  "CLAUSE_NAME": "CLAUSE_NAME-29197259",
  "CLAUSE_CODE": "CLAUSE_CODE-29197259",
  "CLAUSE_TEXT": "CLAUSE_TEXT-29197259",
  "LOB_ID": 97
}


### MDM.Clauses
DELETE {{server}}/odata/v4/mdm/Clauses/29197259
Content-Type: application/json
{{auth}}


### MDM.CommissionTypes
GET {{server}}/odata/v4/mdm/CommissionTypes
Content-Type: application/json
{{auth}}


### MDM.CommissionTypes
POST {{server}}/odata/v4/mdm/CommissionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 21886044,
  "createdAt": "2003-03-23T20:00:00.000Z",
  "createdBy": "createdBy-21886044",
  "modifiedAt": "2001-04-28T20:00:00.000Z",
  "modifiedBy": "modifiedBy-21886044",
  "ACTIVE": true,
  "DELETED": true,
  "COMMISSIONTYPE_KEY": "IONTYPE_KEY-21886044",
  "COMMISSIONTYPE_DESCRIPTION": "COMMISSIONTYPE_DESCRIPTION-21886044",
  "GROUP_NAME": "GROUP_NAME-21886044",
  "SECTIONTYPE_KEY": "IONTYPE_KEY-21886044",
  "SECTIONTYPE_DESCRIPTION": "SECTIONTYPE_DESCRIPTION-21886044",
  "CASCADELEVEL_KEY": "DELEVEL_KEY-21886044",
  "CASCADELEVEL_DESCRIPTION": "CASCADELEVEL_DESCRIPTION-21886044",
  "FLAG": "6044",
  "APPLICABLE": "APPLICABLE-21886044"
}


### MDM.CommissionTypes
PATCH {{server}}/odata/v4/mdm/CommissionTypes/21886044
Content-Type: application/json
{{auth}}

{
  "ID": 21886044,
  "createdAt": "2003-03-23T20:00:00.000Z",
  "createdBy": "createdBy-21886044",
  "modifiedAt": "2001-04-28T20:00:00.000Z",
  "modifiedBy": "modifiedBy-21886044",
  "ACTIVE": true,
  "DELETED": true,
  "COMMISSIONTYPE_KEY": "IONTYPE_KEY-21886044",
  "COMMISSIONTYPE_DESCRIPTION": "COMMISSIONTYPE_DESCRIPTION-21886044",
  "GROUP_NAME": "GROUP_NAME-21886044",
  "SECTIONTYPE_KEY": "IONTYPE_KEY-21886044",
  "SECTIONTYPE_DESCRIPTION": "SECTIONTYPE_DESCRIPTION-21886044",
  "CASCADELEVEL_KEY": "DELEVEL_KEY-21886044",
  "CASCADELEVEL_DESCRIPTION": "CASCADELEVEL_DESCRIPTION-21886044",
  "FLAG": "6044",
  "APPLICABLE": "APPLICABLE-21886044"
}


### MDM.CommissionTypes
DELETE {{server}}/odata/v4/mdm/CommissionTypes/21886044
Content-Type: application/json
{{auth}}


### MDM.DefaultCollectionTypes
GET {{server}}/odata/v4/mdm/DefaultCollectionTypes
Content-Type: application/json
{{auth}}


### MDM.DefaultCollectionTypes
POST {{server}}/odata/v4/mdm/DefaultCollectionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 9723982,
  "createdAt": "2022-12-13T20:00:00.000Z",
  "createdBy": "createdBy-9723982",
  "modifiedAt": "2006-08-07T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9723982",
  "ACTIVE": true,
  "DELETED": true,
  "DEFAULTCOLLECTIONTYPE_KEY": "TIONTYPE_KEY-9723982",
  "DEFAULTCOLLECTIONTYPE_DESCRIPTION": "DEFAULTCOLLECTIONTYPE_DESCRIPTION-9723982",
  "MEMBER": "2",
  "QSMEMBER": "2"
}


### MDM.DefaultCollectionTypes
PATCH {{server}}/odata/v4/mdm/DefaultCollectionTypes/9723982
Content-Type: application/json
{{auth}}

{
  "ID": 9723982,
  "createdAt": "2022-12-13T20:00:00.000Z",
  "createdBy": "createdBy-9723982",
  "modifiedAt": "2006-08-07T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9723982",
  "ACTIVE": true,
  "DELETED": true,
  "DEFAULTCOLLECTIONTYPE_KEY": "TIONTYPE_KEY-9723982",
  "DEFAULTCOLLECTIONTYPE_DESCRIPTION": "DEFAULTCOLLECTIONTYPE_DESCRIPTION-9723982",
  "MEMBER": "2",
  "QSMEMBER": "2"
}


### MDM.DefaultCollectionTypes
DELETE {{server}}/odata/v4/mdm/DefaultCollectionTypes/9723982
Content-Type: application/json
{{auth}}


### MDM.PayPremiumToTypes
GET {{server}}/odata/v4/mdm/PayPremiumToTypes
Content-Type: application/json
{{auth}}


### MDM.PayPremiumToTypes
POST {{server}}/odata/v4/mdm/PayPremiumToTypes
Content-Type: application/json
{{auth}}

{
  "ID": 12342087,
  "createdAt": "2013-08-21T20:00:00.000Z",
  "createdBy": "createdBy-12342087",
  "modifiedAt": "2015-01-30T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12342087",
  "ACTIVE": false,
  "DELETED": false,
  "PAYPREMIUMTOTYPE_KEY": "MTOTYPE_KEY-12342087",
  "PAYPREMIUMTOTYPE_DESCRIPTION": "PAYPREMIUMTOTYPE_DESCRIPTION-12342087",
  "MEMBER": "7",
  "QSMEMBER": "7"
}


### MDM.PayPremiumToTypes
PATCH {{server}}/odata/v4/mdm/PayPremiumToTypes/12342087
Content-Type: application/json
{{auth}}

{
  "ID": 12342087,
  "createdAt": "2013-08-21T20:00:00.000Z",
  "createdBy": "createdBy-12342087",
  "modifiedAt": "2015-01-30T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12342087",
  "ACTIVE": false,
  "DELETED": false,
  "PAYPREMIUMTOTYPE_KEY": "MTOTYPE_KEY-12342087",
  "PAYPREMIUMTOTYPE_DESCRIPTION": "PAYPREMIUMTOTYPE_DESCRIPTION-12342087",
  "MEMBER": "7",
  "QSMEMBER": "7"
}


### MDM.PayPremiumToTypes
DELETE {{server}}/odata/v4/mdm/PayPremiumToTypes/12342087
Content-Type: application/json
{{auth}}


### MDM.ClaimCollectFromTypes
GET {{server}}/odata/v4/mdm/ClaimCollectFromTypes
Content-Type: application/json
{{auth}}


### MDM.ClaimCollectFromTypes
POST {{server}}/odata/v4/mdm/ClaimCollectFromTypes
Content-Type: application/json
{{auth}}

{
  "ID": 4105840,
  "createdAt": "2008-10-28T20:00:00.000Z",
  "createdBy": "createdBy-4105840",
  "modifiedAt": "2014-10-04T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4105840",
  "ACTIVE": true,
  "DELETED": true,
  "CLAIMCOLLECTFROMTYPE_KEY": "FROMTYPE_KEY-4105840",
  "CLAIMCOLLECTFROMTYPE_DESCRIPTION": "CLAIMCOLLECTFROMTYPE_DESCRIPTION-4105840",
  "MEMBER": "0",
  "QSMEMBER": "0"
}


### MDM.ClaimCollectFromTypes
PATCH {{server}}/odata/v4/mdm/ClaimCollectFromTypes/4105840
Content-Type: application/json
{{auth}}

{
  "ID": 4105840,
  "createdAt": "2008-10-28T20:00:00.000Z",
  "createdBy": "createdBy-4105840",
  "modifiedAt": "2014-10-04T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4105840",
  "ACTIVE": true,
  "DELETED": true,
  "CLAIMCOLLECTFROMTYPE_KEY": "FROMTYPE_KEY-4105840",
  "CLAIMCOLLECTFROMTYPE_DESCRIPTION": "CLAIMCOLLECTFROMTYPE_DESCRIPTION-4105840",
  "MEMBER": "0",
  "QSMEMBER": "0"
}


### MDM.ClaimCollectFromTypes
DELETE {{server}}/odata/v4/mdm/ClaimCollectFromTypes/4105840
Content-Type: application/json
{{auth}}


### MDM.CollectionTypes
GET {{server}}/odata/v4/mdm/CollectionTypes
Content-Type: application/json
{{auth}}


### MDM.CollectionTypes
POST {{server}}/odata/v4/mdm/CollectionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 23116510,
  "createdAt": "2004-09-28T20:00:00.000Z",
  "createdBy": "createdBy-23116510",
  "modifiedAt": "2003-10-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-23116510",
  "ACTIVE": true,
  "DELETED": true,
  "KEY": "Y-23116510",
  "DESCRIPTION": "DESCRIPTION-23116510"
}


### MDM.CollectionTypes
PATCH {{server}}/odata/v4/mdm/CollectionTypes/23116510
Content-Type: application/json
{{auth}}

{
  "ID": 23116510,
  "createdAt": "2004-09-28T20:00:00.000Z",
  "createdBy": "createdBy-23116510",
  "modifiedAt": "2003-10-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-23116510",
  "ACTIVE": true,
  "DELETED": true,
  "KEY": "Y-23116510",
  "DESCRIPTION": "DESCRIPTION-23116510"
}


### MDM.CollectionTypes
DELETE {{server}}/odata/v4/mdm/CollectionTypes/23116510
Content-Type: application/json
{{auth}}


### MDM.PlacementTypes
GET {{server}}/odata/v4/mdm/PlacementTypes
Content-Type: application/json
{{auth}}


### MDM.PlacementTypes
POST {{server}}/odata/v4/mdm/PlacementTypes
Content-Type: application/json
{{auth}}

{
  "ID": 6777718,
  "createdAt": "2005-11-05T20:00:00.000Z",
  "createdBy": "createdBy-6777718",
  "modifiedAt": "2020-08-20T20:00:00.000Z",
  "modifiedBy": "modifiedBy-6777718",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 16,
  "PLACEMENT_NAME": "ACEMENT_NAME-6777718",
  "PLACEMENT_DESCRIPTION": "PLACEMENT_DESCRIPTION-6777718"
}


### MDM.PlacementTypes
PATCH {{server}}/odata/v4/mdm/PlacementTypes/6777718
Content-Type: application/json
{{auth}}

{
  "ID": 6777718,
  "createdAt": "2005-11-05T20:00:00.000Z",
  "createdBy": "createdBy-6777718",
  "modifiedAt": "2020-08-20T20:00:00.000Z",
  "modifiedBy": "modifiedBy-6777718",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 16,
  "PLACEMENT_NAME": "ACEMENT_NAME-6777718",
  "PLACEMENT_DESCRIPTION": "PLACEMENT_DESCRIPTION-6777718"
}


### MDM.PlacementTypes
DELETE {{server}}/odata/v4/mdm/PlacementTypes/6777718
Content-Type: application/json
{{auth}}


### MDM.ExposureTypes
GET {{server}}/odata/v4/mdm/ExposureTypes
Content-Type: application/json
{{auth}}


### MDM.ExposureTypes
POST {{server}}/odata/v4/mdm/ExposureTypes
Content-Type: application/json
{{auth}}

{
  "ID": 23981264,
  "createdAt": "2018-01-01T20:00:00.000Z",
  "createdBy": "createdBy-23981264",
  "modifiedAt": "2010-08-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-23981264",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 92,
  "LOB_NAME": "LOB_NAME-23981264",
  "EXPOSURE_TYPE": "EXPOSURE_TYPE-23981264",
  "INTRISK_CODE": "INTRISK_CODE-23981264",
  "VALUE": "E-23981264"
}


### MDM.ExposureTypes
PATCH {{server}}/odata/v4/mdm/ExposureTypes/23981264
Content-Type: application/json
{{auth}}

{
  "ID": 23981264,
  "createdAt": "2018-01-01T20:00:00.000Z",
  "createdBy": "createdBy-23981264",
  "modifiedAt": "2010-08-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-23981264",
  "ACTIVE": true,
  "DELETED": true,
  "LOB_ID": 92,
  "LOB_NAME": "LOB_NAME-23981264",
  "EXPOSURE_TYPE": "EXPOSURE_TYPE-23981264",
  "INTRISK_CODE": "INTRISK_CODE-23981264",
  "VALUE": "E-23981264"
}


### MDM.ExposureTypes
DELETE {{server}}/odata/v4/mdm/ExposureTypes/23981264
Content-Type: application/json
{{auth}}


### MDM.Offices
GET {{server}}/odata/v4/mdm/Offices
Content-Type: application/json
{{auth}}


### MDM.Offices
POST {{server}}/odata/v4/mdm/Offices
Content-Type: application/json
{{auth}}

{
  "ID": 9062246,
  "createdAt": "2018-02-26T20:00:00.000Z",
  "createdBy": "createdBy-9062246",
  "modifiedAt": "2003-12-11T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9062246",
  "ACTIVE": true,
  "DELETED": true,
  "OFFICE_KEY": "OFFICE_KEY-9062246",
  "OFFICE_DESCRIPTION": "OFFICE_DESCRIPTION-9062246"
}


### MDM.Offices
PATCH {{server}}/odata/v4/mdm/Offices/9062246
Content-Type: application/json
{{auth}}

{
  "ID": 9062246,
  "createdAt": "2018-02-26T20:00:00.000Z",
  "createdBy": "createdBy-9062246",
  "modifiedAt": "2003-12-11T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9062246",
  "ACTIVE": true,
  "DELETED": true,
  "OFFICE_KEY": "OFFICE_KEY-9062246",
  "OFFICE_DESCRIPTION": "OFFICE_DESCRIPTION-9062246"
}


### MDM.Offices
DELETE {{server}}/odata/v4/mdm/Offices/9062246
Content-Type: application/json
{{auth}}


### MDM.DeductionTypes
GET {{server}}/odata/v4/mdm/DeductionTypes
Content-Type: application/json
{{auth}}


### MDM.DeductionTypes
POST {{server}}/odata/v4/mdm/DeductionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 11531909,
  "createdAt": "2002-03-25T20:00:00.000Z",
  "createdBy": "createdBy-11531909",
  "modifiedAt": "2016-09-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-11531909",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_TYPE_KEY": "ON_TYPE_KEY-11531909",
  "DEDUCTION_TYPE_DESCRIPTION": "DEDUCTION_TYPE_DESCRIPTION-11531909",
  "DEDUCTION_TYPE": "UCTION_TYPE-11531909",
  "LOB_ID": 17,
  "AVIATION_DEDUCTIONS": "AVIATION_DEDUCTIONS-11531909",
  "SPACE_DEDUCTIONS": "SPACE_DEDUCTIONS-11531909",
  "ENERGY_DEDUCTIONS": "ENERGY_DEDUCTIONS-11531909"
}


### MDM.DeductionTypes
PATCH {{server}}/odata/v4/mdm/DeductionTypes/11531909
Content-Type: application/json
{{auth}}

{
  "ID": 11531909,
  "createdAt": "2002-03-25T20:00:00.000Z",
  "createdBy": "createdBy-11531909",
  "modifiedAt": "2016-09-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-11531909",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_TYPE_KEY": "ON_TYPE_KEY-11531909",
  "DEDUCTION_TYPE_DESCRIPTION": "DEDUCTION_TYPE_DESCRIPTION-11531909",
  "DEDUCTION_TYPE": "UCTION_TYPE-11531909",
  "LOB_ID": 17,
  "AVIATION_DEDUCTIONS": "AVIATION_DEDUCTIONS-11531909",
  "SPACE_DEDUCTIONS": "SPACE_DEDUCTIONS-11531909",
  "ENERGY_DEDUCTIONS": "ENERGY_DEDUCTIONS-11531909"
}


### MDM.DeductionTypes
DELETE {{server}}/odata/v4/mdm/DeductionTypes/11531909
Content-Type: application/json
{{auth}}


### MDM.DeductionBasis
GET {{server}}/odata/v4/mdm/DeductionBasis
Content-Type: application/json
{{auth}}


### MDM.DeductionBasis
POST {{server}}/odata/v4/mdm/DeductionBasis
Content-Type: application/json
{{auth}}

{
  "ID": 25278717,
  "createdAt": "2007-01-26T20:00:00.000Z",
  "createdBy": "createdBy-25278717",
  "modifiedAt": "2022-08-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25278717",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_BASIS_KEY": "N_BASIS_KEY-25278717",
  "DEDUCTION_BASIS_DESCRIPTION": "DEDUCTION_BASIS_DESCRIPTION-25278717",
  "DEDUCTION_BASIS_TYPE": "_BASIS_TYPE-25278717",
  "LOB_ID": 19,
  "AVIATION_DEDUCTIONS": "AVIATION_DEDUCTIONS-25278717",
  "SPACE_DEDUCTIONS": "SPACE_DEDUCTIONS-25278717",
  "ENERGY_DEDUCTIONS": "ENERGY_DEDUCTIONS-25278717"
}


### MDM.DeductionBasis
PATCH {{server}}/odata/v4/mdm/DeductionBasis/25278717
Content-Type: application/json
{{auth}}

{
  "ID": 25278717,
  "createdAt": "2007-01-26T20:00:00.000Z",
  "createdBy": "createdBy-25278717",
  "modifiedAt": "2022-08-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25278717",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_BASIS_KEY": "N_BASIS_KEY-25278717",
  "DEDUCTION_BASIS_DESCRIPTION": "DEDUCTION_BASIS_DESCRIPTION-25278717",
  "DEDUCTION_BASIS_TYPE": "_BASIS_TYPE-25278717",
  "LOB_ID": 19,
  "AVIATION_DEDUCTIONS": "AVIATION_DEDUCTIONS-25278717",
  "SPACE_DEDUCTIONS": "SPACE_DEDUCTIONS-25278717",
  "ENERGY_DEDUCTIONS": "ENERGY_DEDUCTIONS-25278717"
}


### MDM.DeductionBasis
DELETE {{server}}/odata/v4/mdm/DeductionBasis/25278717
Content-Type: application/json
{{auth}}


### MDM.Products
GET {{server}}/odata/v4/mdm/Products
Content-Type: application/json
{{auth}}


### MDM.Products
POST {{server}}/odata/v4/mdm/Products
Content-Type: application/json
{{auth}}

{
  "ID": 30877452,
  "createdAt": "2011-09-10T20:00:00.000Z",
  "createdBy": "createdBy-30877452",
  "modifiedAt": "2021-10-27T20:00:00.000Z",
  "modifiedBy": "modifiedBy-30877452",
  "ACTIVE": true,
  "DELETED": true,
  "PRODUCT_NAME": "PRODUCT_NAME-30877452",
  "LOB_ID": 33
}


### MDM.Products
PATCH {{server}}/odata/v4/mdm/Products/30877452
Content-Type: application/json
{{auth}}

{
  "ID": 30877452,
  "createdAt": "2011-09-10T20:00:00.000Z",
  "createdBy": "createdBy-30877452",
  "modifiedAt": "2021-10-27T20:00:00.000Z",
  "modifiedBy": "modifiedBy-30877452",
  "ACTIVE": true,
  "DELETED": true,
  "PRODUCT_NAME": "PRODUCT_NAME-30877452",
  "LOB_ID": 33
}


### MDM.Products
DELETE {{server}}/odata/v4/mdm/Products/30877452
Content-Type: application/json
{{auth}}


### MDM.ParticipationSpecialists
GET {{server}}/odata/v4/mdm/ParticipationSpecialists
Content-Type: application/json
{{auth}}


### MDM.ParticipationSpecialists
POST {{server}}/odata/v4/mdm/ParticipationSpecialists
Content-Type: application/json
{{auth}}

{
  "ID": 2286381,
  "createdAt": "2009-07-08T20:00:00.000Z",
  "createdBy": "createdBy-2286381",
  "modifiedAt": "2003-04-21T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2286381",
  "ACTIVE": false,
  "DELETED": false,
  "USER_NAME": "USER_NAME-2286381",
  "LOB_ID": 10,
  "LOB_NAME": "ME-2286381"
}


### MDM.ParticipationSpecialists
PATCH {{server}}/odata/v4/mdm/ParticipationSpecialists/2286381
Content-Type: application/json
{{auth}}

{
  "ID": 2286381,
  "createdAt": "2009-07-08T20:00:00.000Z",
  "createdBy": "createdBy-2286381",
  "modifiedAt": "2003-04-21T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2286381",
  "ACTIVE": false,
  "DELETED": false,
  "USER_NAME": "USER_NAME-2286381",
  "LOB_ID": 10,
  "LOB_NAME": "ME-2286381"
}


### MDM.ParticipationSpecialists
DELETE {{server}}/odata/v4/mdm/ParticipationSpecialists/2286381
Content-Type: application/json
{{auth}}


### MDM.CoverTypes
GET {{server}}/odata/v4/mdm/CoverTypes
Content-Type: application/json
{{auth}}


### MDM.CoverTypes
POST {{server}}/odata/v4/mdm/CoverTypes
Content-Type: application/json
{{auth}}

{
  "ID": 8997998,
  "createdAt": "2017-01-19T20:00:00.000Z",
  "createdBy": "createdBy-8997998",
  "modifiedAt": "2006-03-15T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8997998",
  "ACTIVE": true,
  "DELETED": true,
  "COVERTYPE_KEY": 93,
  "COVERTYPE_CD": "COVERTYPE_CD-8997998",
  "LOB_ID": 13,
  "EXTCOVERAGES": "EXTCOVERAGES-8997998"
}


### MDM.CoverTypes
PATCH {{server}}/odata/v4/mdm/CoverTypes/8997998
Content-Type: application/json
{{auth}}

{
  "ID": 8997998,
  "createdAt": "2017-01-19T20:00:00.000Z",
  "createdBy": "createdBy-8997998",
  "modifiedAt": "2006-03-15T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8997998",
  "ACTIVE": true,
  "DELETED": true,
  "COVERTYPE_KEY": 93,
  "COVERTYPE_CD": "COVERTYPE_CD-8997998",
  "LOB_ID": 13,
  "EXTCOVERAGES": "EXTCOVERAGES-8997998"
}


### MDM.CoverTypes
DELETE {{server}}/odata/v4/mdm/CoverTypes/8997998
Content-Type: application/json
{{auth}}


### MDM.HighRiskJurisdictions
GET {{server}}/odata/v4/mdm/HighRiskJurisdictions
Content-Type: application/json
{{auth}}


### MDM.HighRiskJurisdictions
POST {{server}}/odata/v4/mdm/HighRiskJurisdictions
Content-Type: application/json
{{auth}}

{
  "ID": 27504656,
  "createdAt": "2018-06-13T20:00:00.000Z",
  "createdBy": "createdBy-27504656",
  "modifiedAt": "2016-08-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-27504656",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "656",
  "UN": "UN-27504656",
  "EU": "EU-27504656",
  "US": "US-27504656",
  "FATF": "FATF-27504656",
  "AGREEMENT": "AGREEMENT-27504656",
  "ARAB_LEAGUE": "ARAB_LEAGUE-27504656",
  "ItsCountry": {
    "ID": 19244388
  }
}


### MDM.HighRiskJurisdictions
PATCH {{server}}/odata/v4/mdm/HighRiskJurisdictions/27504656
Content-Type: application/json
{{auth}}

{
  "ID": 27504656,
  "createdAt": "2018-06-13T20:00:00.000Z",
  "createdBy": "createdBy-27504656",
  "modifiedAt": "2016-08-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-27504656",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "656",
  "UN": "UN-27504656",
  "EU": "EU-27504656",
  "US": "US-27504656",
  "FATF": "FATF-27504656",
  "AGREEMENT": "AGREEMENT-27504656",
  "ARAB_LEAGUE": "ARAB_LEAGUE-27504656",
  "ItsCountry": {
    "ID": 19244388
  }
}


### MDM.HighRiskJurisdictions
DELETE {{server}}/odata/v4/mdm/HighRiskJurisdictions/27504656
Content-Type: application/json
{{auth}}


### MDM.DeductionLookups
GET {{server}}/odata/v4/mdm/DeductionLookups
Content-Type: application/json
{{auth}}


### MDM.DeductionLookups
POST {{server}}/odata/v4/mdm/DeductionLookups
Content-Type: application/json
{{auth}}

{
  "ID": 4916311,
  "createdAt": "2022-09-02T20:00:00.000Z",
  "createdBy": "createdBy-4916311",
  "modifiedAt": "2018-11-18T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4916311",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_TYPE": "DUCTION_TYPE-4916311",
  "DEDUCTION_BASIS": "UCTION_BASIS-4916311"
}


### MDM.DeductionLookups
PATCH {{server}}/odata/v4/mdm/DeductionLookups/4916311
Content-Type: application/json
{{auth}}

{
  "ID": 4916311,
  "createdAt": "2022-09-02T20:00:00.000Z",
  "createdBy": "createdBy-4916311",
  "modifiedAt": "2018-11-18T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4916311",
  "ACTIVE": false,
  "DELETED": false,
  "DEDUCTION_TYPE": "DUCTION_TYPE-4916311",
  "DEDUCTION_BASIS": "UCTION_BASIS-4916311"
}


### MDM.DeductionLookups
DELETE {{server}}/odata/v4/mdm/DeductionLookups/4916311
Content-Type: application/json
{{auth}}


### MDM.BudgetTypesMaster
GET {{server}}/odata/v4/mdm/BudgetTypesMaster
Content-Type: application/json
{{auth}}


### MDM.BudgetTypesMaster
POST {{server}}/odata/v4/mdm/BudgetTypesMaster
Content-Type: application/json
{{auth}}

{
  "ID": 15877586,
  "createdAt": "2022-05-24T20:00:00.000Z",
  "createdBy": "createdBy-15877586",
  "modifiedAt": "2004-10-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-15877586",
  "ACTIVE": true,
  "DELETED": true,
  "DESCRIPTION": "DESCRIPTION-15877586"
}


### MDM.BudgetTypesMaster
PATCH {{server}}/odata/v4/mdm/BudgetTypesMaster/15877586
Content-Type: application/json
{{auth}}

{
  "ID": 15877586,
  "createdAt": "2022-05-24T20:00:00.000Z",
  "createdBy": "createdBy-15877586",
  "modifiedAt": "2004-10-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-15877586",
  "ACTIVE": true,
  "DELETED": true,
  "DESCRIPTION": "DESCRIPTION-15877586"
}


### MDM.BudgetTypesMaster
DELETE {{server}}/odata/v4/mdm/BudgetTypesMaster/15877586
Content-Type: application/json
{{auth}}


### MDM.RefEquipements
GET {{server}}/odata/v4/mdm/RefEquipements
Content-Type: application/json
{{auth}}


### MDM.RefEquipements
POST {{server}}/odata/v4/mdm/RefEquipements
Content-Type: application/json
{{auth}}

{
  "ID": 2307509,
  "createdAt": "2000-08-10T20:00:00.000Z",
  "createdBy": "createdBy-2307509",
  "modifiedAt": "2006-12-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2307509",
  "ACTIVE": false,
  "DELETED": false,
  "EQUIPMENT_KEY": "EQUIPMENT_KEY-2307509",
  "DESCRIPTION": "DESCRIPTION-2307509"
}


### MDM.RefEquipements
PATCH {{server}}/odata/v4/mdm/RefEquipements/2307509
Content-Type: application/json
{{auth}}

{
  "ID": 2307509,
  "createdAt": "2000-08-10T20:00:00.000Z",
  "createdBy": "createdBy-2307509",
  "modifiedAt": "2006-12-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2307509",
  "ACTIVE": false,
  "DELETED": false,
  "EQUIPMENT_KEY": "EQUIPMENT_KEY-2307509",
  "DESCRIPTION": "DESCRIPTION-2307509"
}


### MDM.RefEquipements
DELETE {{server}}/odata/v4/mdm/RefEquipements/2307509
Content-Type: application/json
{{auth}}


### MDM.CommissionRules
GET {{server}}/odata/v4/mdm/CommissionRules
Content-Type: application/json
{{auth}}


### MDM.CommissionRules
POST {{server}}/odata/v4/mdm/CommissionRules
Content-Type: application/json
{{auth}}

{
  "ID": 7313469,
  "createdAt": "2009-02-06T20:00:00.000Z",
  "createdBy": "createdBy-7313469",
  "modifiedAt": "2004-08-21T20:00:00.000Z",
  "modifiedBy": "modifiedBy-7313469",
  "ACTIVE": false,
  "DELETED": false,
  "COMMISSIONRULE_KEY": "SIONRULE_KEY-7313469",
  "COMMISSIONRULE_DESCRIPTION": "COMMISSIONRULE_DESCRIPTION-7313469"
}


### MDM.CommissionRules
PATCH {{server}}/odata/v4/mdm/CommissionRules/7313469
Content-Type: application/json
{{auth}}

{
  "ID": 7313469,
  "createdAt": "2009-02-06T20:00:00.000Z",
  "createdBy": "createdBy-7313469",
  "modifiedAt": "2004-08-21T20:00:00.000Z",
  "modifiedBy": "modifiedBy-7313469",
  "ACTIVE": false,
  "DELETED": false,
  "COMMISSIONRULE_KEY": "SIONRULE_KEY-7313469",
  "COMMISSIONRULE_DESCRIPTION": "COMMISSIONRULE_DESCRIPTION-7313469"
}


### MDM.CommissionRules
DELETE {{server}}/odata/v4/mdm/CommissionRules/7313469
Content-Type: application/json
{{auth}}


### MDM.ConditionOperators
GET {{server}}/odata/v4/mdm/ConditionOperators
Content-Type: application/json
{{auth}}


### MDM.ConditionOperators
POST {{server}}/odata/v4/mdm/ConditionOperators
Content-Type: application/json
{{auth}}

{
  "ID": 19368153,
  "createdAt": "2006-11-15T20:00:00.000Z",
  "createdBy": "createdBy-19368153",
  "modifiedAt": "2019-11-17T20:00:00.000Z",
  "modifiedBy": "modifiedBy-19368153",
  "ACTIVE": false,
  "DELETED": false,
  "OPERATOR": "OPERATOR-19368153",
  "OPERATOR_DESCRIPTION": "OPERATOR_DESCRIPTION-19368153"
}


### MDM.ConditionOperators
PATCH {{server}}/odata/v4/mdm/ConditionOperators/19368153
Content-Type: application/json
{{auth}}

{
  "ID": 19368153,
  "createdAt": "2006-11-15T20:00:00.000Z",
  "createdBy": "createdBy-19368153",
  "modifiedAt": "2019-11-17T20:00:00.000Z",
  "modifiedBy": "modifiedBy-19368153",
  "ACTIVE": false,
  "DELETED": false,
  "OPERATOR": "OPERATOR-19368153",
  "OPERATOR_DESCRIPTION": "OPERATOR_DESCRIPTION-19368153"
}


### MDM.ConditionOperators
DELETE {{server}}/odata/v4/mdm/ConditionOperators/19368153
Content-Type: application/json
{{auth}}


### MDM.Currencies
GET {{server}}/odata/v4/mdm/Currencies
Content-Type: application/json
{{auth}}


### MDM.Currencies
POST {{server}}/odata/v4/mdm/Currencies
Content-Type: application/json
{{auth}}

{
  "ID": 24379992,
  "createdAt": "2012-12-09T20:00:00.000Z",
  "createdBy": "createdBy-24379992",
  "modifiedAt": "2020-08-14T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24379992",
  "ACTIVE": true,
  "DELETED": true,
  "CURRENCY_CODE": "992"
}


### MDM.Currencies
PATCH {{server}}/odata/v4/mdm/Currencies/24379992
Content-Type: application/json
{{auth}}

{
  "ID": 24379992,
  "createdAt": "2012-12-09T20:00:00.000Z",
  "createdBy": "createdBy-24379992",
  "modifiedAt": "2020-08-14T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24379992",
  "ACTIVE": true,
  "DELETED": true,
  "CURRENCY_CODE": "992"
}


### MDM.Currencies
DELETE {{server}}/odata/v4/mdm/Currencies/24379992
Content-Type: application/json
{{auth}}


### MDM.AgreementStatus
GET {{server}}/odata/v4/mdm/AgreementStatus
Content-Type: application/json
{{auth}}


### MDM.AgreementStatus
POST {{server}}/odata/v4/mdm/AgreementStatus
Content-Type: application/json
{{auth}}

{
  "ID": 6750721,
  "createdAt": "2012-09-10T20:00:00.000Z",
  "createdBy": "createdBy-6750721",
  "modifiedAt": "2010-12-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-6750721",
  "ACTIVE": false,
  "DELETED": false,
  "STATUS_KEY": "STATUS_KEY-6750721",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-6750721"
}


### MDM.AgreementStatus
PATCH {{server}}/odata/v4/mdm/AgreementStatus/6750721
Content-Type: application/json
{{auth}}

{
  "ID": 6750721,
  "createdAt": "2012-09-10T20:00:00.000Z",
  "createdBy": "createdBy-6750721",
  "modifiedAt": "2010-12-02T20:00:00.000Z",
  "modifiedBy": "modifiedBy-6750721",
  "ACTIVE": false,
  "DELETED": false,
  "STATUS_KEY": "STATUS_KEY-6750721",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-6750721"
}


### MDM.AgreementStatus
DELETE {{server}}/odata/v4/mdm/AgreementStatus/6750721
Content-Type: application/json
{{auth}}


### MDM.StampStatus
GET {{server}}/odata/v4/mdm/StampStatus
Content-Type: application/json
{{auth}}


### MDM.StampStatus
POST {{server}}/odata/v4/mdm/StampStatus
Content-Type: application/json
{{auth}}

{
  "ID": 29902640,
  "createdAt": "2003-06-11T20:00:00.000Z",
  "createdBy": "createdBy-29902640",
  "modifiedAt": "2009-05-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-29902640",
  "ACTIVE": true,
  "DELETED": true,
  "STATUS_KEY": "STATUS_KEY-29902640",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-29902640"
}


### MDM.StampStatus
PATCH {{server}}/odata/v4/mdm/StampStatus/29902640
Content-Type: application/json
{{auth}}

{
  "ID": 29902640,
  "createdAt": "2003-06-11T20:00:00.000Z",
  "createdBy": "createdBy-29902640",
  "modifiedAt": "2009-05-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-29902640",
  "ACTIVE": true,
  "DELETED": true,
  "STATUS_KEY": "STATUS_KEY-29902640",
  "STATUS_DESCRIPTION": "STATUS_DESCRIPTION-29902640"
}


### MDM.StampStatus
DELETE {{server}}/odata/v4/mdm/StampStatus/29902640
Content-Type: application/json
{{auth}}


### MDM.MasterSLips
GET {{server}}/odata/v4/mdm/MasterSLips
Content-Type: application/json
{{auth}}


### MDM.MasterSLips
POST {{server}}/odata/v4/mdm/MasterSLips
Content-Type: application/json
{{auth}}

{
  "ID": 25099596,
  "createdAt": "2017-02-23T20:00:00.000Z",
  "createdBy": "createdBy-25099596",
  "modifiedAt": "2005-10-29T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25099596",
  "ACTIVE": true,
  "DELETED": true,
  "MASTER_SLIP_KEY": "ER_SLIP_KEY-25099596",
  "MASTER_SLIP_VALUE": "MASTER_SLIP_VALUE-25099596",
  "LOB": "LOB-25099596"
}


### MDM.MasterSLips
PATCH {{server}}/odata/v4/mdm/MasterSLips/25099596
Content-Type: application/json
{{auth}}

{
  "ID": 25099596,
  "createdAt": "2017-02-23T20:00:00.000Z",
  "createdBy": "createdBy-25099596",
  "modifiedAt": "2005-10-29T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25099596",
  "ACTIVE": true,
  "DELETED": true,
  "MASTER_SLIP_KEY": "ER_SLIP_KEY-25099596",
  "MASTER_SLIP_VALUE": "MASTER_SLIP_VALUE-25099596",
  "LOB": "LOB-25099596"
}


### MDM.MasterSLips
DELETE {{server}}/odata/v4/mdm/MasterSLips/25099596
Content-Type: application/json
{{auth}}


### MDM.MasterSlipYears
GET {{server}}/odata/v4/mdm/MasterSlipYears
Content-Type: application/json
{{auth}}


### MDM.MasterSlipYears
POST {{server}}/odata/v4/mdm/MasterSlipYears
Content-Type: application/json
{{auth}}

{
  "ID": 30744436,
  "createdAt": "2010-10-04T20:00:00.000Z",
  "createdBy": "createdBy-30744436",
  "modifiedAt": "2003-05-31T20:00:00.000Z",
  "modifiedBy": "modifiedBy-30744436",
  "ACTIVE": true,
  "DELETED": true,
  "MASTER_SLIP_YEAR_KEY": "IP_YEAR_KEY-30744436",
  "MASTER_SLIP_YEAR_VALUE": "MASTER_SLIP_YEAR_VALUE-30744436",
  "MASTER_SLIP_YEAR_DESCRIPTION": "DESCRIPTION-30744436"
}


### MDM.MasterSlipYears
PATCH {{server}}/odata/v4/mdm/MasterSlipYears/30744436
Content-Type: application/json
{{auth}}

{
  "ID": 30744436,
  "createdAt": "2010-10-04T20:00:00.000Z",
  "createdBy": "createdBy-30744436",
  "modifiedAt": "2003-05-31T20:00:00.000Z",
  "modifiedBy": "modifiedBy-30744436",
  "ACTIVE": true,
  "DELETED": true,
  "MASTER_SLIP_YEAR_KEY": "IP_YEAR_KEY-30744436",
  "MASTER_SLIP_YEAR_VALUE": "MASTER_SLIP_YEAR_VALUE-30744436",
  "MASTER_SLIP_YEAR_DESCRIPTION": "DESCRIPTION-30744436"
}


### MDM.MasterSlipYears
DELETE {{server}}/odata/v4/mdm/MasterSlipYears/30744436
Content-Type: application/json
{{auth}}


### MDM.States
GET {{server}}/odata/v4/mdm/States
Content-Type: application/json
{{auth}}


### MDM.States
POST {{server}}/odata/v4/mdm/States
Content-Type: application/json
{{auth}}

{
  "ID": 2353028,
  "createdAt": "2007-10-29T20:00:00.000Z",
  "createdBy": "createdBy-2353028",
  "modifiedAt": "2000-05-09T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2353028",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "028",
  "STATE_CD": "028",
  "STATE_NAME": "STATE_NAME-2353028"
}


### MDM.States
PATCH {{server}}/odata/v4/mdm/States/2353028
Content-Type: application/json
{{auth}}

{
  "ID": 2353028,
  "createdAt": "2007-10-29T20:00:00.000Z",
  "createdBy": "createdBy-2353028",
  "modifiedAt": "2000-05-09T20:00:00.000Z",
  "modifiedBy": "modifiedBy-2353028",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "028",
  "STATE_CD": "028",
  "STATE_NAME": "STATE_NAME-2353028"
}


### MDM.States
DELETE {{server}}/odata/v4/mdm/States/2353028
Content-Type: application/json
{{auth}}


### MDM.Taxes
GET {{server}}/odata/v4/mdm/Taxes
Content-Type: application/json
{{auth}}


### MDM.Taxes
POST {{server}}/odata/v4/mdm/Taxes
Content-Type: application/json
{{auth}}

{
  "ID": 18377598,
  "createdAt": "2013-10-12T20:00:00.000Z",
  "createdBy": "createdBy-18377598",
  "modifiedAt": "2005-10-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-18377598",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "598",
  "TAXTYPE_CD": "77598",
  "ADMINISTEREDBY_CD": "598",
  "PAYABLEBY_CD": "598",
  "DIRECT_TAX_VL": 27.130249,
  "REINSURANCE_TAX_VL": 67.91425,
  "VALIDFROM_DT": "2009-07-04T20:00:00.000Z",
  "VALIDTO_DT": "2002-04-30T20:00:00.000Z",
  "TAXBASIS_CD": "D-18377598",
  "TAXBASIS_NAME": "TAXBASIS_NAME-18377598",
  "LEGACY": true,
  "LLRISKCODE_ID": 27,
  "INTRISK_ID": 66,
  "ItsCountry": {
    "ID": 1992245
  },
  "ItsTaxType": {
    "ID": 5207428,
    "TAXTYPE_CD": "07428"
  },
  "ItsPayableBy": {
    "ID": 8077135,
    "PROCESSOR_CD": "135"
  },
  "ItsAdministeredBy": {
    "ID": 26706475,
    "PROCESSOR_CD": "475"
  },
  "ItsTaxBasis": {
    "ID": 22378015,
    "TAXBASIS_CD": "s-22378015"
  },
  "ItsLLoydsRiskCode": {
    "ID": 30127082
  },
  "ItsInternalRiskCode": {
    "ID": 14494367
  }
}


### MDM.Taxes
PATCH {{server}}/odata/v4/mdm/Taxes/18377598
Content-Type: application/json
{{auth}}

{
  "ID": 18377598,
  "createdAt": "2013-10-12T20:00:00.000Z",
  "createdBy": "createdBy-18377598",
  "modifiedAt": "2005-10-23T20:00:00.000Z",
  "modifiedBy": "modifiedBy-18377598",
  "ACTIVE": true,
  "DELETED": true,
  "COUNTRY_CD": "598",
  "TAXTYPE_CD": "77598",
  "ADMINISTEREDBY_CD": "598",
  "PAYABLEBY_CD": "598",
  "DIRECT_TAX_VL": 27.130249,
  "REINSURANCE_TAX_VL": 67.91425,
  "VALIDFROM_DT": "2009-07-04T20:00:00.000Z",
  "VALIDTO_DT": "2002-04-30T20:00:00.000Z",
  "TAXBASIS_CD": "D-18377598",
  "TAXBASIS_NAME": "TAXBASIS_NAME-18377598",
  "LEGACY": true,
  "LLRISKCODE_ID": 27,
  "INTRISK_ID": 66,
  "ItsCountry": {
    "ID": 1992245
  },
  "ItsTaxType": {
    "ID": 5207428,
    "TAXTYPE_CD": "07428"
  },
  "ItsPayableBy": {
    "ID": 8077135,
    "PROCESSOR_CD": "135"
  },
  "ItsAdministeredBy": {
    "ID": 26706475,
    "PROCESSOR_CD": "475"
  },
  "ItsTaxBasis": {
    "ID": 22378015,
    "TAXBASIS_CD": "s-22378015"
  },
  "ItsLLoydsRiskCode": {
    "ID": 30127082
  },
  "ItsInternalRiskCode": {
    "ID": 14494367
  }
}


### MDM.Taxes
DELETE {{server}}/odata/v4/mdm/Taxes/18377598
Content-Type: application/json
{{auth}}


### MDM.TaxBasis
GET {{server}}/odata/v4/mdm/TaxBasis
Content-Type: application/json
{{auth}}


### MDM.TaxBasis
POST {{server}}/odata/v4/mdm/TaxBasis
Content-Type: application/json
{{auth}}

{
  "ID": 22378015,
  "TAXBASIS_CD": "s-22378015",
  "createdAt": "2022-03-08T20:00:00.000Z",
  "createdBy": "createdBy-22378015",
  "modifiedAt": "2000-12-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-22378015",
  "ACTIVE": false,
  "DELETED": false,
  "TAXBASIS_NAME": "TAXBASIS_NAME-22378015"
}


### MDM.TaxBasis
PATCH {{server}}/odata/v4/mdm/TaxBasis/22378015
Content-Type: application/json
{{auth}}

{
  "ID": 22378015,
  "TAXBASIS_CD": "s-22378015",
  "createdAt": "2022-03-08T20:00:00.000Z",
  "createdBy": "createdBy-22378015",
  "modifiedAt": "2000-12-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-22378015",
  "ACTIVE": false,
  "DELETED": false,
  "TAXBASIS_NAME": "TAXBASIS_NAME-22378015"
}


### MDM.TaxBasis
DELETE {{server}}/odata/v4/mdm/TaxBasis/22378015
Content-Type: application/json
{{auth}}


### MDM.TaxTypes
GET {{server}}/odata/v4/mdm/TaxTypes
Content-Type: application/json
{{auth}}


### MDM.TaxTypes
POST {{server}}/odata/v4/mdm/TaxTypes
Content-Type: application/json
{{auth}}

{
  "ID": 5207428,
  "TAXTYPE_CD": "07428",
  "createdAt": "2014-07-28T20:00:00.000Z",
  "createdBy": "createdBy-5207428",
  "modifiedAt": "2013-02-03T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5207428",
  "ACTIVE": true,
  "DELETED": true,
  "TAXTYPE_NAME": "TAXTYPE_NAME-5207428"
}


### MDM.TaxTypes
PATCH {{server}}/odata/v4/mdm/TaxTypes/5207428
Content-Type: application/json
{{auth}}

{
  "ID": 5207428,
  "TAXTYPE_CD": "07428",
  "createdAt": "2014-07-28T20:00:00.000Z",
  "createdBy": "createdBy-5207428",
  "modifiedAt": "2013-02-03T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5207428",
  "ACTIVE": true,
  "DELETED": true,
  "TAXTYPE_NAME": "TAXTYPE_NAME-5207428"
}


### MDM.TaxTypes
DELETE {{server}}/odata/v4/mdm/TaxTypes/5207428
Content-Type: application/json
{{auth}}


### MDM.TaxProcessors
GET {{server}}/odata/v4/mdm/TaxProcessors
Content-Type: application/json
{{auth}}


### MDM.TaxProcessors
POST {{server}}/odata/v4/mdm/TaxProcessors
Content-Type: application/json
{{auth}}

{
  "ID": 8077135,
  "PROCESSOR_CD": "135",
  "createdAt": "2003-06-20T20:00:00.000Z",
  "createdBy": "createdBy-8077135",
  "modifiedAt": "2003-08-09T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8077135",
  "ACTIVE": false,
  "DELETED": false,
  "PROCESSOR_NAME": "PROCESSOR_NAME-8077135"
}


### MDM.TaxProcessors
PATCH {{server}}/odata/v4/mdm/TaxProcessors/8077135
Content-Type: application/json
{{auth}}

{
  "ID": 8077135,
  "PROCESSOR_CD": "135",
  "createdAt": "2003-06-20T20:00:00.000Z",
  "createdBy": "createdBy-8077135",
  "modifiedAt": "2003-08-09T20:00:00.000Z",
  "modifiedBy": "modifiedBy-8077135",
  "ACTIVE": false,
  "DELETED": false,
  "PROCESSOR_NAME": "PROCESSOR_NAME-8077135"
}


### MDM.TaxProcessors
DELETE {{server}}/odata/v4/mdm/TaxProcessors/8077135
Content-Type: application/json
{{auth}}


### MDM.PoolUWYCurrencies
GET {{server}}/odata/v4/mdm/PoolUWYCurrencies
Content-Type: application/json
{{auth}}


### MDM.PoolUWYCurrencies
POST {{server}}/odata/v4/mdm/PoolUWYCurrencies
Content-Type: application/json
{{auth}}

{
  "ID": 5009641,
  "createdAt": "2009-01-19T20:00:00.000Z",
  "createdBy": "createdBy-5009641",
  "modifiedAt": "2011-06-08T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5009641",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 20,
  "POOL_ID": 52,
  "POOLUWY_ID": 6,
  "LOB_NAME": "LOB_NAME-5009641",
  "POOL_NAME": "POOL_NAME-5009641",
  "POOL_UWYNAME": "POOL_UWYNAME-5009641",
  "UWYEAR": 1,
  "CURRENCY": "CY-5009641",
  "DEFAULT": "1"
}


### MDM.PoolUWYCurrencies
PATCH {{server}}/odata/v4/mdm/PoolUWYCurrencies/5009641
Content-Type: application/json
{{auth}}

{
  "ID": 5009641,
  "createdAt": "2009-01-19T20:00:00.000Z",
  "createdBy": "createdBy-5009641",
  "modifiedAt": "2011-06-08T20:00:00.000Z",
  "modifiedBy": "modifiedBy-5009641",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 20,
  "POOL_ID": 52,
  "POOLUWY_ID": 6,
  "LOB_NAME": "LOB_NAME-5009641",
  "POOL_NAME": "POOL_NAME-5009641",
  "POOL_UWYNAME": "POOL_UWYNAME-5009641",
  "UWYEAR": 1,
  "CURRENCY": "CY-5009641",
  "DEFAULT": "1"
}


### MDM.PoolUWYCurrencies
DELETE {{server}}/odata/v4/mdm/PoolUWYCurrencies/5009641
Content-Type: application/json
{{auth}}


### MDM.Operations
GET {{server}}/odata/v4/mdm/Operations
Content-Type: application/json
{{auth}}


### MDM.Operations
POST {{server}}/odata/v4/mdm/Operations
Content-Type: application/json
{{auth}}

{
  "ID": 9288988,
  "createdAt": "2001-12-10T20:00:00.000Z",
  "createdBy": "createdBy-9288988",
  "modifiedAt": "2023-03-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9288988",
  "ACTIVE": true,
  "DELETED": true,
  "OPERATION_KEY": 40,
  "OPERATION_CD": "OPERATION_CD-9288988"
}


### MDM.Operations
PATCH {{server}}/odata/v4/mdm/Operations/9288988
Content-Type: application/json
{{auth}}

{
  "ID": 9288988,
  "createdAt": "2001-12-10T20:00:00.000Z",
  "createdBy": "createdBy-9288988",
  "modifiedAt": "2023-03-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy-9288988",
  "ACTIVE": true,
  "DELETED": true,
  "OPERATION_KEY": 40,
  "OPERATION_CD": "OPERATION_CD-9288988"
}


### MDM.Operations
DELETE {{server}}/odata/v4/mdm/Operations/9288988
Content-Type: application/json
{{auth}}


### MDM.AdditionalCommissionTypes
GET {{server}}/odata/v4/mdm/AdditionalCommissionTypes
Content-Type: application/json
{{auth}}


### MDM.AdditionalCommissionTypes
POST {{server}}/odata/v4/mdm/AdditionalCommissionTypes
Content-Type: application/json
{{auth}}

{
  "ID": 24385053,
  "createdAt": "2010-04-30T20:00:00.000Z",
  "createdBy": "createdBy-24385053",
  "modifiedAt": "2003-10-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24385053",
  "ACTIVE": false,
  "DELETED": false,
  "COMMISSIONTYPE_KEY": "IONTYPE_KEY-24385053",
  "COMMISSIONTYPE_DESCRIPTION": "COMMISSIONTYPE_DESCRIPTION-24385053",
  "GROUP_NAME": "GROUP_NAME-24385053",
  "FLAG": "5053"
}


### MDM.AdditionalCommissionTypes
PATCH {{server}}/odata/v4/mdm/AdditionalCommissionTypes/24385053
Content-Type: application/json
{{auth}}

{
  "ID": 24385053,
  "createdAt": "2010-04-30T20:00:00.000Z",
  "createdBy": "createdBy-24385053",
  "modifiedAt": "2003-10-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy-24385053",
  "ACTIVE": false,
  "DELETED": false,
  "COMMISSIONTYPE_KEY": "IONTYPE_KEY-24385053",
  "COMMISSIONTYPE_DESCRIPTION": "COMMISSIONTYPE_DESCRIPTION-24385053",
  "GROUP_NAME": "GROUP_NAME-24385053",
  "FLAG": "5053"
}


### MDM.AdditionalCommissionTypes
DELETE {{server}}/odata/v4/mdm/AdditionalCommissionTypes/24385053
Content-Type: application/json
{{auth}}


### MDM.CatCodes
GET {{server}}/odata/v4/mdm/CatCodes
Content-Type: application/json
{{auth}}


### MDM.SpacePhases
GET {{server}}/odata/v4/mdm/SpacePhases
Content-Type: application/json
{{auth}}


### MDM.SpacePhases
POST {{server}}/odata/v4/mdm/SpacePhases
Content-Type: application/json
{{auth}}

{
  "ID": 25388232,
  "createdAt": "2002-09-11T20:00:00.000Z",
  "createdBy": "createdBy-25388232",
  "modifiedAt": "2020-10-03T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25388232",
  "ACTIVE": true,
  "DELETED": true,
  "SPACE_PHASE_NAME": "SPACE_PHASE_NAME-25388232",
  "ACCUMULATION_LEVEL": "ACCUMULATION_LEVEL-25388232",
  "SPACE_PHASE_NAME_DESCRIPTION": "SPACE_PHASE_NAME_DESCRIPTION-25388232"
}


### MDM.SpacePhases
PATCH {{server}}/odata/v4/mdm/SpacePhases/25388232
Content-Type: application/json
{{auth}}

{
  "ID": 25388232,
  "createdAt": "2002-09-11T20:00:00.000Z",
  "createdBy": "createdBy-25388232",
  "modifiedAt": "2020-10-03T20:00:00.000Z",
  "modifiedBy": "modifiedBy-25388232",
  "ACTIVE": true,
  "DELETED": true,
  "SPACE_PHASE_NAME": "SPACE_PHASE_NAME-25388232",
  "ACCUMULATION_LEVEL": "ACCUMULATION_LEVEL-25388232",
  "SPACE_PHASE_NAME_DESCRIPTION": "SPACE_PHASE_NAME_DESCRIPTION-25388232"
}


### MDM.SpacePhases
DELETE {{server}}/odata/v4/mdm/SpacePhases/25388232
Content-Type: application/json
{{auth}}


### MDM.FormulaMasters
GET {{server}}/odata/v4/mdm/FormulaMasters
Content-Type: application/json
{{auth}}


### MDM.FormulaMasters
POST {{server}}/odata/v4/mdm/FormulaMasters
Content-Type: application/json
{{auth}}

{
  "ID": 143431,
  "createdAt": "2020-03-03T20:00:00.000Z",
  "createdBy": "createdBy-143431",
  "modifiedAt": "2018-04-27T20:00:00.000Z",
  "modifiedBy": "modifiedBy-143431",
  "ACTIVE": false,
  "DELETED": false,
  "FORMULA_NAME": "FORMULA_NAME-143431"
}


### MDM.FormulaMasters
PATCH {{server}}/odata/v4/mdm/FormulaMasters/143431
Content-Type: application/json
{{auth}}

{
  "ID": 143431,
  "createdAt": "2020-03-03T20:00:00.000Z",
  "createdBy": "createdBy-143431",
  "modifiedAt": "2018-04-27T20:00:00.000Z",
  "modifiedBy": "modifiedBy-143431",
  "ACTIVE": false,
  "DELETED": false,
  "FORMULA_NAME": "FORMULA_NAME-143431"
}


### MDM.FormulaMasters
DELETE {{server}}/odata/v4/mdm/FormulaMasters/143431
Content-Type: application/json
{{auth}}


### MDM.FormulaVariables
GET {{server}}/odata/v4/mdm/FormulaVariables
Content-Type: application/json
{{auth}}


### MDM.FormulaVariables
POST {{server}}/odata/v4/mdm/FormulaVariables
Content-Type: application/json
{{auth}}

{
  "ID": 4071685,
  "createdAt": "2014-01-03T20:00:00.000Z",
  "createdBy": "createdBy-4071685",
  "modifiedAt": "2014-05-20T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4071685",
  "ACTIVE": false,
  "DELETED": false,
  "VARIABLE_NAME": "VARIABLE_NAME-4071685"
}


### MDM.FormulaVariables
PATCH {{server}}/odata/v4/mdm/FormulaVariables/4071685
Content-Type: application/json
{{auth}}

{
  "ID": 4071685,
  "createdAt": "2014-01-03T20:00:00.000Z",
  "createdBy": "createdBy-4071685",
  "modifiedAt": "2014-05-20T20:00:00.000Z",
  "modifiedBy": "modifiedBy-4071685",
  "ACTIVE": false,
  "DELETED": false,
  "VARIABLE_NAME": "VARIABLE_NAME-4071685"
}


### MDM.FormulaVariables
DELETE {{server}}/odata/v4/mdm/FormulaVariables/4071685
Content-Type: application/json
{{auth}}


### MDM.FormulaTypes
GET {{server}}/odata/v4/mdm/FormulaTypes
Content-Type: application/json
{{auth}}


### MDM.FormulaTypes
POST {{server}}/odata/v4/mdm/FormulaTypes
Content-Type: application/json
{{auth}}

{
  "ID": 12774058,
  "createdAt": "2011-01-20T20:00:00.000Z",
  "createdBy": "createdBy-12774058",
  "modifiedAt": "2010-04-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12774058",
  "ACTIVE": true,
  "DELETED": true,
  "FORMULA_TYPE": "FORMULA_TYPE-12774058",
  "MARGIN_FLAG": "8"
}


### MDM.FormulaTypes
PATCH {{server}}/odata/v4/mdm/FormulaTypes/12774058
Content-Type: application/json
{{auth}}

{
  "ID": 12774058,
  "createdAt": "2011-01-20T20:00:00.000Z",
  "createdBy": "createdBy-12774058",
  "modifiedAt": "2010-04-19T20:00:00.000Z",
  "modifiedBy": "modifiedBy-12774058",
  "ACTIVE": true,
  "DELETED": true,
  "FORMULA_TYPE": "FORMULA_TYPE-12774058",
  "MARGIN_FLAG": "8"
}


### MDM.FormulaTypes
DELETE {{server}}/odata/v4/mdm/FormulaTypes/12774058
Content-Type: application/json
{{auth}}


### MDM.FormulaDetails
GET {{server}}/odata/v4/mdm/FormulaDetails
Content-Type: application/json
{{auth}}


### MDM.AuthorityTypes
GET {{server}}/odata/v4/mdm/AuthorityTypes
Content-Type: application/json
{{auth}}


### MDM.AuthorityTypes
POST {{server}}/odata/v4/mdm/AuthorityTypes
Content-Type: application/json
{{auth}}

{
  "ID": 10760728,
  "createdAt": "2005-06-08T20:00:00.000Z",
  "createdBy": "createdBy-10760728",
  "modifiedAt": "2006-09-17T20:00:00.000Z",
  "modifiedBy": "modifiedBy-10760728",
  "ACTIVE": true,
  "DELETED": true,
  "AUTHORITYTYPE_KEY": 95,
  "AUTHORITYTYPE_DESCRIPTION": "AUTHORITYTYPE_DESCRIPTION-10760728"
}


### MDM.AuthorityTypes
PATCH {{server}}/odata/v4/mdm/AuthorityTypes/10760728
Content-Type: application/json
{{auth}}

{
  "ID": 10760728,
  "createdAt": "2005-06-08T20:00:00.000Z",
  "createdBy": "createdBy-10760728",
  "modifiedAt": "2006-09-17T20:00:00.000Z",
  "modifiedBy": "modifiedBy-10760728",
  "ACTIVE": true,
  "DELETED": true,
  "AUTHORITYTYPE_KEY": 95,
  "AUTHORITYTYPE_DESCRIPTION": "AUTHORITYTYPE_DESCRIPTION-10760728"
}


### MDM.AuthorityTypes
DELETE {{server}}/odata/v4/mdm/AuthorityTypes/10760728
Content-Type: application/json
{{auth}}


### MDM.Users
GET {{server}}/odata/v4/mdm/Users
Content-Type: application/json
{{auth}}


### MDM.RiskObjectTypes
GET {{server}}/odata/v4/mdm/RiskObjectTypes
Content-Type: application/json
{{auth}}


### MDM.RiskObjectTypes
POST {{server}}/odata/v4/mdm/RiskObjectTypes
Content-Type: application/json
{{auth}}

{
  "ID": 10179659,
  "createdAt": "2018-08-23T20:00:00.000Z",
  "createdBy": "createdBy-10179659",
  "modifiedAt": "2007-03-16T20:00:00.000Z",
  "modifiedBy": "modifiedBy-10179659",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 92,
  "NAME": "NAME-10179659",
  "DESCRIPTION": "DESCRIPTION-10179659"
}


### MDM.RiskObjectTypes
PATCH {{server}}/odata/v4/mdm/RiskObjectTypes/10179659
Content-Type: application/json
{{auth}}

{
  "ID": 10179659,
  "createdAt": "2018-08-23T20:00:00.000Z",
  "createdBy": "createdBy-10179659",
  "modifiedAt": "2007-03-16T20:00:00.000Z",
  "modifiedBy": "modifiedBy-10179659",
  "ACTIVE": false,
  "DELETED": false,
  "LOB_ID": 92,
  "NAME": "NAME-10179659",
  "DESCRIPTION": "DESCRIPTION-10179659"
}


### MDM.RiskObjectTypes
DELETE {{server}}/odata/v4/mdm/RiskObjectTypes/10179659
Content-Type: application/json
{{auth}}


### MDM.CommissionPayTo
GET {{server}}/odata/v4/mdm/CommissionPayTo
Content-Type: application/json
{{auth}}


### MDM.CommissionPayTo
POST {{server}}/odata/v4/mdm/CommissionPayTo
Content-Type: application/json
{{auth}}

{
  "ID": 14064730,
  "createdAt": "2018-05-15T20:00:00.000Z",
  "createdBy": "createdBy-14064730",
  "modifiedAt": "2007-11-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-14064730",
  "ACTIVE": true,
  "DELETED": true,
  "COMMPAYTO_KEY": "MMPAYTO_KEY-14064730",
  "COMMPAYTO_NAME": "COMMPAYTO_NAME-14064730"
}


### MDM.CommissionPayTo
PATCH {{server}}/odata/v4/mdm/CommissionPayTo/14064730
Content-Type: application/json
{{auth}}

{
  "ID": 14064730,
  "createdAt": "2018-05-15T20:00:00.000Z",
  "createdBy": "createdBy-14064730",
  "modifiedAt": "2007-11-12T20:00:00.000Z",
  "modifiedBy": "modifiedBy-14064730",
  "ACTIVE": true,
  "DELETED": true,
  "COMMPAYTO_KEY": "MMPAYTO_KEY-14064730",
  "COMMPAYTO_NAME": "COMMPAYTO_NAME-14064730"
}


### MDM.CommissionPayTo
DELETE {{server}}/odata/v4/mdm/CommissionPayTo/14064730
Content-Type: application/json
{{auth}}


### MDM.CommissionCollectedOn
GET {{server}}/odata/v4/mdm/CommissionCollectedOn
Content-Type: application/json
{{auth}}


### MDM.CommissionCollectedOn
POST {{server}}/odata/v4/mdm/CommissionCollectedOn
Content-Type: application/json
{{auth}}

{
  "ID": 19673511,
  "createdAt": "2014-12-13T20:00:00.000Z",
  "createdBy": "createdBy-19673511",
  "modifiedAt": "2004-01-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-19673511",
  "ACTIVE": false,
  "DELETED": false,
  "COMMCOLLECTON_KEY": "LLECTON_KEY-19673511",
  "COMMCOLLECTON_NAME": "COMMCOLLECTON_NAME-19673511"
}


### MDM.CommissionCollectedOn
PATCH {{server}}/odata/v4/mdm/CommissionCollectedOn/19673511
Content-Type: application/json
{{auth}}

{
  "ID": 19673511,
  "createdAt": "2014-12-13T20:00:00.000Z",
  "createdBy": "createdBy-19673511",
  "modifiedAt": "2004-01-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-19673511",
  "ACTIVE": false,
  "DELETED": false,
  "COMMCOLLECTON_KEY": "LLECTON_KEY-19673511",
  "COMMCOLLECTON_NAME": "COMMCOLLECTON_NAME-19673511"
}


### MDM.CommissionCollectedOn
DELETE {{server}}/odata/v4/mdm/CommissionCollectedOn/19673511
Content-Type: application/json
{{auth}}


### MDM.Divisions
GET {{server}}/odata/v4/mdm/Divisions
Content-Type: application/json
{{auth}}


### MDM.Divisions
POST {{server}}/odata/v4/mdm/Divisions
Content-Type: application/json
{{auth}}

{
  "ID": 3202843,
  "createdAt": "2010-01-22T20:00:00.000Z",
  "createdBy": "createdBy-3202843",
  "modifiedAt": "2015-02-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-3202843",
  "ACTIVE": false,
  "DELETED": false,
  "DIVISION_CODE": "43",
  "DIVISION_NAME": "DIVISION_NAME-3202843"
}


### MDM.Divisions
PATCH {{server}}/odata/v4/mdm/Divisions/3202843
Content-Type: application/json
{{auth}}

{
  "ID": 3202843,
  "createdAt": "2010-01-22T20:00:00.000Z",
  "createdBy": "createdBy-3202843",
  "modifiedAt": "2015-02-05T20:00:00.000Z",
  "modifiedBy": "modifiedBy-3202843",
  "ACTIVE": false,
  "DELETED": false,
  "DIVISION_CODE": "43",
  "DIVISION_NAME": "DIVISION_NAME-3202843"
}


### MDM.Divisions
DELETE {{server}}/odata/v4/mdm/Divisions/3202843
Content-Type: application/json
{{auth}}


### MDM.Product
GET {{server}}/odata/v4/mdm/Product
Content-Type: application/json
{{auth}}


### MDM.Product
POST {{server}}/odata/v4/mdm/Product
Content-Type: application/json
{{auth}}

{
  "ID": 28371298,
  "createdAt": "2000-10-09T20:00:00.000Z",
  "createdBy": "createdBy-28371298",
  "modifiedAt": "2014-04-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-28371298",
  "ACTIVE": true,
  "DELETED": true,
  "NAME": "NAME-28371298",
  "DESCRIPTION": "DESCRIPTION-28371298",
  "BOTTOM_UP": true,
  "CODE": "298",
  "LOB_ID": 69,
  "ItsLineofBusiness": {
    "ID": 14229159
  }
}


### MDM.Product
PATCH {{server}}/odata/v4/mdm/Product/28371298
Content-Type: application/json
{{auth}}

{
  "ID": 28371298,
  "createdAt": "2000-10-09T20:00:00.000Z",
  "createdBy": "createdBy-28371298",
  "modifiedAt": "2014-04-01T20:00:00.000Z",
  "modifiedBy": "modifiedBy-28371298",
  "ACTIVE": true,
  "DELETED": true,
  "NAME": "NAME-28371298",
  "DESCRIPTION": "DESCRIPTION-28371298",
  "BOTTOM_UP": true,
  "CODE": "298",
  "LOB_ID": 69,
  "ItsLineofBusiness": {
    "ID": 14229159
  }
}


### MDM.Product
DELETE {{server}}/odata/v4/mdm/Product/28371298
Content-Type: application/json
{{auth}}


### MDM.refreshMasterData
POST {{server}}/odata/v4/mdm/refreshMasterData
Content-Type: application/json
{{auth}}

{
  "namespace": null,
  "destinationPrefix": null,
  "tableNames": null
}
