# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CDS Mocha tests

on:
  pull_request:
    branches: [ "Development" ]

jobs:
  mocha-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Install Dependencies
        run: bun install chai@^4.4.1 chai-as-promised@^7.1.2 chai-http@^4.4.0 chai-subset@^1.6.0 mocha@^10.4.0 express@^4.18.2 cors@^2.8.5 morgan@^1.10.0 @sap/cds@^7.0.0

      - name: Start test
        run: bun run test
